version: '3.8'

services:
  itg-docverse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      # Mount the database file to persist data
      - ./apis/itg_docuverse.db:/api/itg_docuverse.db
    restart: unless-stopped

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - itg-docverse
    restart: unless-stopped
    profiles:
      - production
